#!/usr/bin/env bash
# ============================================================================
# TrailCurrent Headwaters — first-login setup wizard
#
# Runs on the first interactive SSH session when $HOME/.env is missing.
# Prompts for credentials, auto-generates cryptographic secrets, writes .env,
# and starts the Docker stack.
#
# The trigger lives in /etc/profile.d/first-login-hook.sh.
# ============================================================================

set -e

DEPLOY_DIR="$HOME"
ENV_FILE="$DEPLOY_DIR/.env"
SENTINEL="$HOME/.headwaters-setup-complete"

# Only run if .env is missing AND we haven't run the wizard before
[ -f "$ENV_FILE" ] && { touch "$SENTINEL"; return 0 2>/dev/null || exit 0; }
[ -f "$SENTINEL" ] && { return 0 2>/dev/null || exit 0; }
[ -t 0 ] || { return 0 2>/dev/null || exit 0; }

echo ""
echo "============================================="
echo "  TrailCurrent Headwaters — First-Time Setup"
echo "============================================="
echo ""
echo "No configuration found. Let's set up your device."
echo "Cryptographic secrets will be auto-generated."
echo ""

prompt() {
    local var_name="$1" prompt_text="$2" default="$3" value=""
    if [ -n "$default" ]; then
        read -rp "  $prompt_text [$default]: " value
        value="${value:-$default}"
    else
        while [ -z "$value" ]; do
            read -rp "  $prompt_text: " value
            [ -z "$value" ] && echo "    (required)"
        done
    fi
    eval "$var_name=\"\$value\""
}

prompt_password() {
    local var_name="$1" prompt_text="$2" value="" confirm=""
    while true; do
        read -srp "  $prompt_text: " value; echo ""
        if [ -z "$value" ]; then
            echo "    (required)"
            continue
        fi
        read -srp "  Confirm: " confirm; echo ""
        [ "$value" = "$confirm" ] && break
        echo "    Passwords don't match, try again."
    done
    eval "$var_name=\"\$value\""
}

TLS_CERT_HOSTNAME="headwaters.local"

echo "── MQTT Broker ──"
prompt MQTT_USERNAME "MQTT username" "trailcurrent"
prompt_password MQTT_PASSWORD "MQTT password"
echo ""

echo "── System Admin ──"
prompt_password ADMIN_PASSWORD "Admin password (for web UI)"
echo ""

echo "── Generating secrets ──"
ENCRYPTION_KEY=$(openssl rand -hex 32)
echo "  ENCRYPTION_KEY generated (32 bytes)"
echo ""

cat > "$ENV_FILE" <<EOF
# Generated by TrailCurrent first-login setup on $(date -I)

# MQTT Configuration
MQTT_BROKER_URL=mqtts://mosquitto:8883
MQTT_USERNAME=$MQTT_USERNAME
MQTT_PASSWORD=$MQTT_PASSWORD

# Encryption & Security
ENCRYPTION_KEY=$ENCRYPTION_KEY
ADMIN_PASSWORD=$ADMIN_PASSWORD

# API Configuration
API_PORT=3000
FRONTEND_PORT=443

# Database Configuration
DB_PATH=/app/data/invehicle.db
MONGODB_HOST=localhost
MONGODB_PORT=27017
MONGODB_DATABASE=trailcurrent

# Network Configuration
TLS_CERT_HOSTNAME=$TLS_CERT_HOSTNAME

# Environment
NODE_ENV=production
EOF
chmod 600 "$ENV_FILE"
echo "  .env written to $ENV_FILE"

# local_code .env with host-facing MQTT URL
if [ -d "$HOME/local_code" ]; then
    cp "$ENV_FILE" "$HOME/local_code/.env"
    sed -i "s|mqtts://mosquitto:|mqtts://${TLS_CERT_HOSTNAME}:|g" "$HOME/local_code/.env"
    echo "  local_code/.env written (host-facing MQTT URL)"

    [ -f "$HOME/data/keys/ca.pem" ] && cp "$HOME/data/keys/ca.pem" "$HOME/local_code/ca.pem"
fi

# Install CA into the system trust store so host-side Python scripts validate TLS
if [ -f "$HOME/data/keys/ca.crt" ]; then
    SYSTEM_CA="/usr/local/share/ca-certificates/trailcurrent-ca.crt"
    if [ ! -f "$SYSTEM_CA" ] || ! cmp -s "$HOME/data/keys/ca.crt" "$SYSTEM_CA"; then
        echo ""
        echo "── Installing CA certificate to system trust store ──"
        sudo cp "$HOME/data/keys/ca.crt" "$SYSTEM_CA"
        sudo update-ca-certificates > /dev/null 2>&1
        echo "  Done"
    fi
fi

echo ""
echo "── Starting services ──"
cd "$DEPLOY_DIR"

# On a --minimal validation image, no app container tarballs are baked in, so
# `docker compose up` would fall back to pulling from Docker Hub and fail on
# the private TrailCurrent images. Detect that case and skip compose entirely.
BUILD_MODE="full"
[ -f /etc/headwaters-release ] && . /etc/headwaters-release 2>/dev/null || true
BUILD_MODE="${HEADWATERS_BUILD_MODE:-full}"

if [ "$BUILD_MODE" = "minimal" ]; then
    echo "  MINIMAL build: skipping 'docker compose up' — no app containers in this image."
    echo "  To bring up services on a production image, reflash with a non-minimal build."
else
    echo "  Starting Docker containers..."
    docker compose up -d --no-build --remove-orphans
fi

# sudo is NOPASSWD for trailcurrent (see hook 4 of rootfs.jsonnet). Do NOT
# silence stderr — if sudo ever starts prompting for a password, we want
# that failure to be immediately visible, not to silently hang the wizard.
sudo systemctl restart cantomqtt.service          || echo "  WARNING: cantomqtt restart failed"
sudo systemctl restart discovery-mdns.service     || echo "  WARNING: discovery-mdns restart failed"
sudo systemctl restart deployment-watcher.service || echo "  WARNING: deployment-watcher restart failed"
echo "  systemd services restarted"

touch "$SENTINEL"

echo ""
echo "============================================="
echo "  Setup complete!"
echo "============================================="
echo ""
echo "  Access the application at:"
echo "    https://$TLS_CERT_HOSTNAME"
echo ""
echo "  Docker status:"
docker compose ps --format "table {{.Name}}\t{{.Status}}" 2>/dev/null || docker compose ps
echo ""
echo "  Useful commands:"
echo "    docker compose logs -f           # Docker logs"
echo "    sudo journalctl -u cantomqtt -f  # CAN-to-MQTT logs"
echo ""

# ── CA certificate for browser trust ─────────────────────────────────
CA_CERT="$HOME/data/keys/ca.pem"
if [ -f "$CA_CERT" ]; then
    echo "============================================="
    echo "  IMPORTANT: Install CA Certificate"
    echo "============================================="
    echo ""
    echo "  Your browser needs the TrailCurrent CA certificate"
    echo "  to securely connect (HTTPS and WebSockets)."
    echo ""
    echo "  Save the block below as trailcurrent-ca.pem, then:"
    echo "    - Chrome/Edge: Settings → Privacy & Security → Security"
    echo "      → Manage certificates → Authorities → Import"
    echo "    - Firefox: Settings → Privacy & Security → Certificates"
    echo "      → View Certificates → Authorities → Import"
    echo "      → check \"Trust this CA to identify websites\""
    echo "    - macOS: double-click the .pem, set to \"Always Trust\""
    echo "    - Windows: rename to .crt, Install → Local Machine"
    echo "      → Trusted Root Certification Authorities"
    echo ""
    echo "  ── Begin Certificate ──"
    echo ""
    cat "$CA_CERT"
    echo ""
    echo "  ── End Certificate ──"
    echo ""
fi
